name: clean_arch_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  page_transition: ^2.2.1
  freezed: ^2.5.8
  build_runner: ^2.4.13
  json_serializable: ^6.0.1
  injectable: ^2.5.0
  http: ^1.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  injectable_generator: ^2.6.2
  shared_preferences: ^2.5.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.0.1
  freezed: ^2.5.8
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/default-photo.jpg
